apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: blank-panther-dotnet-basic
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:97186cee5bda33ac31fa664f70d5b5e65a6b4b84@sha256:9eb4bb60e532382fbf078daa57148f7fd5c3bc9dca72736793e0993c5cbcee9e
        name: container-image  
